known_sequences = {
    "Telomeric sequence": "TTAGGG",
    "rRNA sequence": "GAGGAGGAGGAG",
    # "Regulatory sequence": "GGCCTG",
    # "CAG repeat sequence": "CAG",
    # "CTG repeat sequence": "CTG",
    # "CGG repeat sequence": "CGG",
    # "GAA repeat sequence": "GAA",
    # "AC repeat sequence": "ACACACACACAC",
    # "AG repeat sequence": "AGAGAGAGAGAG",
    # "TG repeat sequence": "TGGAGGAGGAGG",
    # "CCTG repeat sequence": "CCTG",
    # "LINE1 transposon element": "LINE1",
    # "Alu transposon element": "Alu",
    # "SINE transposon element": "SINE",
    # "LTR transposon element": "LTR",
    # "MIR transposon element": "MIR",
    # "MER11 transposon element": "MER11",
    # "HERV transposon element": "HERV",
    # "Tc1 transposon element": "Tc1",
    # "Mariner transposon element": "Mariner",
    # "B1 transposon element": "B1",
    # "B2 transposon element": "B2",
    # "B4 transposon element": "B4",
    # "B5 transposon element": "B5",
    # "MITE transposon element": "MITE",
    # "TIR transposon element": "TIR",
    # "TSD transposon element": "TSD",
    # "RTE transposon element": "RTE",
    # "R1 transposon element": "R1",
    # "R2 transposon element": "R2",
    # "R3 transposon element": "R3",
    # "R4 transposon element": "R4",
    # "R5 transposon element": "R5",
    # "R6 transposon element": "R6",
    # "R7 transposon element": "R7",
    # "R8 transposon element": "R8",
    # "R9 transposon element": "R9",
    # "R10 transposon element": "R10",
}
